name: Deploy Node.js app to AWS EC2 via ECR

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        run: |
          IMAGE_URI=797320053116.dkr.ecr.us-east-1.amazonaws.com/backend-node-v1:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: SSH into EC2 and deploy container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop backend-node || true
            docker rm backend-node || true
            docker pull 797320053116.dkr.ecr.us-east-1.amazonaws.com/backend-node-v1:latest
            docker run -d -p 80:3000 --name backend-node 797320053116.dkr.ecr.us-east-1.amazonaws.com/backend-node-v1:latest
